name: python-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - xlrd
  - scikit-learn
  - plotly
  - statsmodel
  - scipy
  - researchpy
